# Generated by Django 4.2.4 on 2023-08-17 07:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productpictures',
            options={'verbose_name': '商品の画像', 'verbose_name_plural': '商品の画像'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='producttypes',
            options={'verbose_name': 'カテゴリー', 'verbose_name_plural': 'カテゴリー'},
        ),
        migrations.AlterModelOptions(
            name='traders',
            options={'verbose_name': '業者', 'verbose_name_plural': '業者'},
        ),
        migrations.AddField(
            model_name='producttypes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttypes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='productpictures',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='画像名'),
        ),
        migrations.AlterField(
            model_name='productpictures',
            name='picture',
            field=models.FileField(upload_to='product_pictures/', verbose_name='画像'),
        ),
        migrations.AlterField(
            model_name='productpictures',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='名前'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_picture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productpictures', verbose_name='写真'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.producttypes', verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='products',
            name='proper_stock',
            field=models.IntegerField(verbose_name='最大在庫数'),
        ),
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.IntegerField(verbose_name='在庫数'),
        ),
        migrations.AlterField(
            model_name='products',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.traders', verbose_name='業者'),
        ),
        migrations.AlterField(
            model_name='products',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='producttypes',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='カテゴリー'),
        ),
        migrations.AlterField(
            model_name='traders',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='traders',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='業者'),
        ),
        migrations.AlterField(
            model_name='traders',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
